const {chromium}=require('/Users/olira/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const path=require('path'),assert=require('assert');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{
const page=await browser.newPage({viewport:{width:1280,height:1000}}),errors=[],posts=[];
page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{sessionStorage.setItem('access','mock');sessionStorage.setItem('expires',String(Date.now()+900000));});
await page.route('https://portal.test/**',route=>{const name=new URL(route.request().url()).pathname.slice(1)||'index.html';return name==='config.json'?route.fulfill({json:{siteUrl:'https://portal.test',apiUrl:'https://api.test',clientId:'client',authUrl:'https://auth.test'}}):route.fulfill({path:path.join(__dirname,'../site',name)});});
await page.route('https://api.test/**',route=>{const url=new URL(route.request().url()),method=route.request().method(),headers={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,content-type','Access-Control-Allow-Methods':'GET,POST,PATCH,OPTIONS'};if(method==='OPTIONS')return route.fulfill({status:204,headers});let data={};if(method==='POST'){data=route.request().postDataJSON();posts.push({path:url.pathname,data});}let result=[];
if(url.pathname==='/me')result={sub:'owner',email:'admin@olrstech.com',role:'super',permissions:['onboard','view_all','manage_admins','manage_mailboxes','manage_users'],provisioningEnabled:true,mailboxEnabled:true,allowedMailboxes:['it','hr','safety','sales','payroll'].map(x=>x+'@olrstech.com')};
if(url.pathname==='/requests'&&method==='POST')result={id:'request'};
if(url.pathname==='/users/search')result=data.username?{id:'inspect',operation:'Inspect',status:'Complete',message:'Ready',result:{ready:true,profile:{objectId:'object',username:'cronaldo',firstName:'Chris',lastName:'Ronaldo',department:'Operations',jobTitle:'Coordinator',managerEmail:'',email:'cronaldo@olrstech.com',enabled:true,protected:false},access:[{address:'it@olrstech.com',fullAccess:true,sendOnBehalf:false,externalFullAccess:false,externalSendOnBehalf:false}]}}:{id:'search',operation:data.browse?'List':'Search',status:'Complete',message:'Ready',result:{total:1,nextCursor:'',users:[{username:'cronaldo',name:'Chris Ronaldo',email:'cronaldo@olrstech.com',department:'Operations',enabled:true}]}};
if(url.pathname==='/users/profile')result={id:'profile',operation:'UpdateProfile',status:'Complete',message:'Employee saved',result:{}};
if(url.pathname==='/users/access')result={id:'apply',operation:'Apply',status:'Complete',message:'Access verified',result:{}};
return route.fulfill({headers,json:result});});
await page.goto('https://portal.test');await page.getByRole('heading',{name:'Onboarding overview'}).waitFor();await page.locator('nav [data-page="employee"]').click();
for(const [label,value] of [['First name','Chris'],['Last name','Ronaldo'],['Username','cronaldo'],['Department','Operations']])await page.getByLabel(label,{exact:true}).fill(value);
await page.locator('[data-mailbox="it@olrstech.com"]').check();await page.locator('[data-behalf="it@olrstech.com"]').selectOption('true');
await page.getByRole('button',{name:'Review onboarding',exact:true}).click();await page.getByRole('button',{name:'Submit onboarding',exact:true}).click();await page.getByRole('heading',{name:'Review onboarding status'}).waitFor();assert.deepEqual(posts.find(p=>p.path==='/requests').data.mailboxAccess,[{address:'it@olrstech.com',sendOnBehalf:true}]);
await page.locator('nav [data-page="users"]').click();await page.getByRole('button',{name:'Manage access',exact:true}).waitFor();assert(posts.some(p=>p.path==='/users/search'&&p.data.browse===true));await page.getByLabel('Find employee').fill('chris');await page.getByRole('button',{name:'Find users'}).click();await page.getByRole('button',{name:'Manage access',exact:true}).click();await page.getByRole('heading',{name:'Microsoft 365 · Shared mailbox permissions'}).waitFor();await page.locator('[data-mailbox="it@olrstech.com"]').uncheck();await page.locator('[data-mailbox="hr@olrstech.com"]').check();
for(const width of [1280,390]){await page.setViewportSize({width,height:1000});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(__dirname,'../.build/mailbox-users-'+width+'.png'),fullPage:true});}
await page.getByRole('button',{name:'Review access changes'}).click();await page.getByRole('button',{name:'Apply access changes'}).click();assert.deepEqual(posts.find(p=>p.path==='/users/access').data,{inspectionId:'inspect',mailboxAccess:[{address:'hr@olrstech.com',sendOnBehalf:false}]});await page.getByRole('button',{name:'Manage access',exact:true}).click();await page.locator('#ad-profile-form input[name="department"]').fill('Sales');await page.getByRole('button',{name:'Review employee changes'}).click();await page.getByRole('button',{name:'Save employee details'}).click();assert(posts.some(p=>p.path==='/users/profile'&&p.data.department==='Sales'));assert.deepEqual(errors,[]);
console.log('Passed: one-submit mailbox selection, user search, access removal/addition, desktop/mobile layout. Mock accounts only.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
